[package]
name = "ver-pg"
version = "0.1.0"
authors = ["James Connolly <jimmy@1024bees.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex ="*"
clap = "3.0.0-beta.2"
lazy_static = "*"
